server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml         # mybatis配置文件所在路径
  type-aliases-package: com.youngnzhi.springcloud.entities   # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                      # mapper映射文件

spring:
  application:
    name: microservicecloud-dept01                            #eureka服务注册中心列表显示的application name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8&useSSL=false              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#eureka客户端配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #A-1 单机版配置
      #defaultZone: http://localhost:7001/eureka  # eureka服务端已经配置的服务注册中心地址
      #A-2 eureka集群配置，client添加所有服务端注册地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001   #实例名称 eureka服务注册中心列表status显示的服务名称(主机名称:服务名称修改)
    prefer-ip-address: true  # 访问路径可以显示IP地址

#微服务info信息配置
info:
  app.name: microservicecloud-dept8001
  company.name: youngnzhiPTD
  user.name: youngnzhi
  build.artifactId: $project.artifactId$
  build.version: $project.version$
