server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/

#开启 支持hystrix服务降级 start
feign:
  hystrix:
    enabled: true
#开启 支持hystrix服务降级 end