server:
  port: 7001


#eureka服务端配置
eureka:
  instance:
    #A-1单机版eureka服务端配置
    #hostname: localhost #eureka服务端的实例名称

    #A-2集群版eureka服务端配置 找到C:\Windows\System32\drivers\etc路径下的hosts文件，添加域名配置
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己(服务注册中心自己不用注册自己)
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    #B-1单机版eureka服务端配置
    #serviceUrl:
    #  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

    #B-2集群版eureka服务端配置，设置路径为除当前eureka之外的其他eureka服务地址
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  #eureka自我保护模式
  #server:
  #  enable-self-preservation: false #测试环境自我保护模式关闭
